<a href="https://colab.research.google.com/github/noircir/TensorFlow-Examples/blob/master/TF1_00_Syntax_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TF Syntax Basics

In [0]:
import tensorflow as tf

In [0]:
print(tf.__version__)

1.15.0


In [0]:
hello = tf.constant("Hello")
world = tf.constant("World")

In [0]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [0]:
with tf.Session() as sess:
  result = sess.run(hello+world)  # or s1 = hello + world;  session.run(s1)

In [0]:
print(result)

b'HelloWorld'


## Addition

In [0]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [0]:
with tf.Session() as sess:
  result = sess.run(tensor_1 + tensor_2)

print(result)

3


## Operations

In [0]:
# constant operation
const = tf.constant(10)

In [0]:
# a matrix to fill with a scalar value
# 4x4 tensor filled with value 10
fill_mat = tf.fill((4,4),10)

In [0]:
myzeros = tf.zeros((4,4))
myones = tf.ones((4,4))
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)


In [0]:
my_operations = [const,fill_mat,myzeros,myones,myrandn,myrandu]

## Interactive session

Only used in notebooks

In [0]:
# only run once
sess = tf.InteractiveSession() 

In [0]:
for op in my_operations:
    print(op.eval()) # or sess.run(op)
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.09672508 -0.18989788  0.452018   -1.3089358 ]
 [-0.42229736  0.39074412 -0.10297     0.7585703 ]
 [ 0.5387069   0.8633109   0.17837074  0.9517313 ]
 [ 0.01825788  0.33625564 -0.20724633  0.73964816]]


[[7.0383465e-01 5.8903348e-01 7.4690652e-01 2.7108669e-02]
 [9.4118834e-02 7.9201162e-01 3.0925405e-01 3.4432828e-01]
 [5.4575527e-01 5.7125843e-01 5.3993523e-01 8.6973107e-01]
 [8.1989264e-01 4.3965816e-01 5.7625771e-04 2.7588487e-02]]




## Matrix Multiplication

In [0]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [0]:
a.shape

TensorShape([Dimension(2), Dimension(2)])

In [0]:
b = tf.constant([[10],[100]])
b.shape

TensorShape([Dimension(2), Dimension(1)])

In [0]:
result = tf.matmul(a,b)

In [0]:
result.eval()

array([[210],
       [430]], dtype=int32)

In [0]:
sess.run(result)

array([[210],
       [430]], dtype=int32)